### ISSUE TITLE
Checks missing on cached push builds (CircleCI)

### ISSUE THREAD

**Issue by cgewecke** [codechecks/monorepo#2]
Just continuing a discussion at `eth-gas-reporter` with @krzkaczor about the codechecks client/server model and the difficulty of identifying "where" one is in the CI cycle. 

My understanding of the issue is:
+ CI caches push builds and applies them to opened pull requests. In these cases, no PR environment variable is set in the Circle container.
+ The codechecks client relies on being able to extract the PR ID from the CI environment.
+ The codechecks client relies on push builds being enabled to save historical data. 

The end result is that checks don't automatically run on the initial commit of a pull request, and anyone who only builds on pull requests won't be able to store data in the codechecks backend.

@krzkaczor has suggested some work-arounds but I'd like to advocate for moving to a system that 
+ subscribes the user's repo to webhooks for push and pull request events
+ does not use `isPR` to toggle reporting on and off. Instead it caches the relevant data on the codechecks backend for all builds (like Circle).
+ does context detection using the server's webhook event history to get the appropriate commit hashes to index data by and trigger checks at the right time. 

This approach is more complicated, difficult to maintain, etc. But it may map more closely to how Github intends its checks API to work. There are also nice UX benefits. For example, when someone opens a PR you could fetch the user's codechecks.yml and immediately trigger 'pending' notifications in their GH UI for whatever they've listed there.

Apologies in advance if I've misunderstood something basic and everything above is nonsense. As in #5 - if you have any interest in volunteer help with something like this, please just let me know. Codechecks is super useful/powerful and there's lots of stuff I'd like to build on top of it.

**Comment by krzkaczor** [comment]
Hey! Thanks for this issue, I totally get that codechecks architecture is somehow weird. But I think it really makes sense in the end and we can fix issues mentioned in this PR pretty soon. 

I agree that artifact recording should happen on every commit despite `isPR` result. This makes sure that later we can always use this data for comparison. 

> does context detection using the server's webhook event history to get the appropriate commit hashes to index data by and trigger checks at the right time.

I think that in your reasoning you assumed that we can calculate the difference between artifacts somehow on our servers when PR is created and upload the result of it to Github. This is now done by codecheck itself during CI. This is not the case. The current approach gives huge flexibility for codecheck creators, for example, one codecheck would generate a gas usage report based on 2 jsons but the other would take 2 directories containing screenshots and generate visual regression report.

I think that coming up with a generic algorithm that would be able to compare two artifacts is very hard if not impossible but maybe, it's worth researching in the future. For example, coming up with some declarative way of report generating. I want to keep my head open for new ideas but currently, I am not sure how this could be supported and this for sure would make backend part much more complicated. 

The current architecture keeps the server side very general yet simple (basically, it's just storing the artifacts, and communicating with GH). This is great because we are not in code execution space but rather just providing building blocks for powerful GH/CI integration. 

As to how to solve this problem right now, I always imagined the solution of `speculative` PR creation. Basically client would always assume that if a commit is not part of the main branch (`master`/`dev`), it is a commit that will be eventually part of PR pointing to the main branch so it can assume that it's a PR. GitHub API allows for checks to be attached to specific commit so it will just work fine. Also it doesn't require any changes to already existing codechecks.

Furthermore, GitHub actions can be triggered on PR creation so then it would result in perfect integration.

That being said, I will think more about your proposal because maybe there is a sweet spot between CC being dump artifact store and allowing users to execute any code on our servers. Maybe one could categorize artifacts (JSONs/images/code chunks) and come up with some nice way to diff them automatically. If you have any ideas let's talk it through 🙏

**Comment by cgewecke** [comment]
Ah ok! Apologies for how unclear I was about this:
> does context detection using the server's webhook event history

I really just mean what you've said is possible with the PR subscription. If that works it's perfect. Also agree that having CC as simple storage and keeping as much code execution in the CI container as possible is a really good design.  

> Maybe one could categorize artifacts (JSONs/images/code chunks) and come up with some nice way to diff them automatically.

Ok I will think about this too . . . it's an interesting idea.

**Comment by krzkaczor** [comment]
@all-contributors please add @cgewecke for plugin, ideas

**Comment by krzkaczor** [comment]
@all-contributors please add @cgewecke for plugin, ideas

**Comment by krzkaczor** [comment]
I am gonna leave here detailed plan for implementing `speculative branch selection` feature right now. 

First of all, we add to `codechecks.yml/json` settings section which contains branch priorities. For example:
```yaml
settings:
	speculative_branches: 
		- dev
		- master
checks:
# ...
```

This means basically that if a commit is being built on any branch that is not listed on `speculative_branches` list and it's not part of a PR it will be treated as it would be a PR targeting first branch from `speculative_branches` list. If it would be a part of a branch on `speculative_branches` list next branch would be chosen as the base. By default `speculative_branches = ['master']`. Also, you can switch off this feature with `speculative_branch_selection = false`.

It basically supports any basic workflows that I can think of. However, this model will break when you wanted to create a PR to totally different (temporary) branch.  I think that it's good enough solution until we find a nicer way (probably by splitting artifact recording and comparison) and of course if PR is already created it will just pick up whatever branch was selected by the user.

Nice thing about this implementation is that it doesn't require any backend changes.
