### ISSUE TITLE
Support Github Actions

### ISSUE THREAD

**Issue by dericgw** [codechecks/monorepo#47]
Are you on board with adding Github as a service provider? I forked the repo and started the work already (just need to finish the tests). If you are okay want to move forward with it, let me know and I will create a PR. It seems to be pretty straight forward.

Thanks!

**Comment by krzkaczor** [comment]
Of course! I wanted to work on this by myself (i just got beta access) but if you can make a PR it would be great 👌🏻

Just to be clear: we are talking about GitHub actions, right?

**Comment by dericgw** [comment]
@krzkaczor Yes, Github Actions.

**Comment by krzkaczor** [comment]
Docs: https://github.com/codechecks/docs/pull/12
Implementation: https://github.com/codechecks/monorepo/pull/50

Currently it doesn't use PR related events because they are issued only once (on PR creation). In our case its just better to run on PUSH event and always act like PR is pointed to `master` branch (or any other branch, specified in settings it's called `speculative branch selection feature`). It's not perfect but I think it's a good start.

Sidenote: one can imagine that codechecks become a proper github action. But I can't find any real benefits for this approach...

**Comment by krzkaczor** [comment]
Thanks again @dericgw your initial implementation was very helpful 👍 

Released as `@codechecks/client@0.1.8`
